[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_GOOGLE_CLIENT_ID = "661157021532-8gpcocl6qfni73rmu9btqsl7lpabpuh4.apps.googleusercontent.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"